#!/bin/sh
ssh  ubuntu@ec2-18-117-74-5.us-east-2.compute.amazonaws.com <<EOF
    cd ~/node-hello
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v17.0.1
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF